package org.study.classroom.mapper;

import org.study.classroom.model.Classroom;
import org.study.classroom.model.ClassroomUser;
import org.study.classroom.utils.Privilege;
import org.study.classroom.utils.Title;

import javax.management.loading.PrivateClassLoader;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface ClassroomUserMapper{
    /**
     * query all classroom users
     * @return
     */
    List<ClassroomUser> selectAll();

    /**
     *
     * @param title student or teacher
     * @return return the list of users specified by title( student or teacher)
     */
    List<ClassroomUser> selectByTitle(Title title);

    /**
     *
     * @param id id is generated by database,and it is unique, and it is different with
     *           the user_id which is student_id or teacher_id.
     * @return return only one classroom user specified by the id
     */
    ClassroomUser selectById(Long id);
    /**
     * query classroom user by specified id
     * @return
     */
    ClassroomUser selectByUserId(Long id);

    List<ClassroomUser> selectByUserIdLike(String id);
    /**
     * query classroom users by user name,
     * result will be none or one element.
     * @param userName
     * @return
     */
    ClassroomUser selectByName(String userName);


    /**
     * insert a classroom user to database
     *
     * @param classroomUser
     * @return
     */
    int insert(ClassroomUser classroomUser);

    List<ClassroomUser> selectByNameLike(String userName);

    int update(ClassroomUser user);

    int deleteById(Long id);

    int deleteAllById(HashMap<String, Object> map);

    int updateAllPrivilege(HashMap<String, Object> map);
}
